### ISSUE TITLE
WARNING: recursion requested but not available

### ISSUE THREAD

**Issue by asbjornenge** [asbjornenge/rainbow-dns#6]
Rainbox-dns does not set the ra header flag to advertise recursion for responses. This apparently breaks resolving for some versions of glibc(?) ref. https://github.com/ioquatix/rubydns/issues/26#issuecomment-40167316

First reported at asbjornenge/rainbow-dock-populator#2

Setting the <code>response.header.ra=1</code> fixes the issue. Is there a downside to just leaving it on no matter what? Should it be behind a flag? I'll try just leaving it on and we'll see how it goes :stuck_out_tongue: 

//cc @simonqbs @miekg

**Comment by miekg** [comment]
You can just enable that, you *are* providing recursion are you?

**Comment by asbjornenge** [comment]
@miekg if people set the --fwdhost flag, yes!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [rainbow-dns] WARNING: recursio..." ]
>@miekg if people set the --fwdhost flag, yes!

ack. Then sure.

I think i just set to the 'true' in SkyDNS no matter what.

/Miek

--
Miek Gieben

**Comment by asbjornenge** [comment]
:+1:
